"""
Deterministic, task-scoped artifact test file generation.

Model: **after** implementation apply, Forge may write a small pytest module under
``tests/forge_generated/`` derived from the task's Forge Validation lines and
``write_file`` targets, then gates run ``python -m pytest`` on that file (plus
optional policy ``test_command``).

If nothing can be inferred, generation is skipped with an explicit reason (fall
back to milestone validation / policy tests only).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from forge.execution.parse import parse_forge_validation_line
from forge.execution.validation_rules import RuleFileContains, RulePathFileContains
from forge.paths import Paths

if TYPE_CHECKING:
    from forge.task_service import Task

GENERATED_SUBDIR = "tests/forge_generated"


@dataclass(frozen=True)
class ArtifactTestGenResult:
    generated: bool
    rel_path: str | None
    message: str
    skipped_reason: str | None = None


_RE_WRITE_FILE = re.compile(
    r"^\s*write_file\s+((?:examples|src|scripts|tests)/[^\s|]+)\s*\|",
    re.IGNORECASE,
)

_TARGET_TO_RELPATH = {
    "requirements": "docs/requirements.md",
    "architecture": "docs/architecture.md",
    "decisions": "docs/decisions.md",
    "milestones": "docs/milestones.md",
}


def _safe_ident(s: str, max_len: int = 40) -> str:
    out = re.sub(r"[^a-zA-Z0-9_]+", "_", s.strip())[:max_len].strip("_")
    return out or "check"


def generate_artifact_tests_for_task(
    milestone_id: int,
    task_id: int,
    task: Task,
) -> ArtifactTestGenResult:
    """
    Build a single pytest module with targeted checks. Returns ``generated=False``
    when no heuristic applies.
    """
    lines: list[str] = [
        '"""Auto-generated by Forge from task validation (do not edit by hand in CI)."""',
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "",
    ]
    tests: list[str] = []
    idx = 0

    for raw in task.forge_validation:
        try:
            rule = parse_forge_validation_line(raw.strip())
        except ValueError:
            continue
        if isinstance(rule, RuleFileContains):
            target = rule.target
            needle = rule.substring
            rel = _TARGET_TO_RELPATH.get(target)
            if rel and needle:
                idx += 1
                fn = f"test_task_validation_file_contains_{idx}_{_safe_ident(target)}"
                tests.append(
                    f"def {fn}():\n"
                    f'    root = Path(__file__).resolve().parents[2]\n'
                    f'    p = root / "{rel}"\n'
                    f"    assert p.is_file(), f'missing {{p}}'\n"
                    f"    text = p.read_text(encoding='utf-8')\n"
                    f"    assert {needle!r} in text\n"
                )
        elif isinstance(rule, RulePathFileContains):
            rel_p, sub = rule.rel_path, rule.substring
            if rel_p and sub and not rel_p.startswith(".."):
                idx += 1
                fn = f"test_task_validation_path_contains_{idx}"
                tests.append(
                    f"def {fn}():\n"
                    f'    root = Path(__file__).resolve().parents[2]\n'
                    f'    p = root / "{rel_p}"\n'
                    f"    assert p.is_file(), f'missing {{p}}'\n"
                    f"    text = p.read_text(encoding='utf-8')\n"
                    f"    assert {sub!r} in text\n"
                )

    for raw in task.forge_actions:
        m3 = _RE_WRITE_FILE.match(raw.strip())
        if m3:
            rel_py = m3.group(1).strip()
            if rel_py.endswith(".py"):
                idx += 1
                fn = f"test_generated_module_compiles_{idx}_{_safe_ident(rel_py)}"
                tests.append(
                    f"def {fn}():\n"
                    f'    root = Path(__file__).resolve().parents[2]\n'
                    f'    p = root / "{rel_py}"\n'
                    f"    assert p.is_file(), f'missing {{p}}'\n"
                    f"    src = p.read_text(encoding='utf-8')\n"
                    f"    compile(src, str(p), 'exec')\n"
                )

    if not tests:
        return ArtifactTestGenResult(
            generated=False,
            rel_path=None,
            message="No artifact test heuristics matched this task (skipped).",
            skipped_reason="no_matching_validation_or_write_file_patterns",
        )

    lines.append("")
    lines.extend(tests)
    lines.append("")

    out_dir = Paths.BASE_DIR / GENERATED_SUBDIR
    out_dir.mkdir(parents=True, exist_ok=True)
    fname = f"test_m{milestone_id}_t{task_id}_artifact.py"
    out_path = out_dir / fname
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        rel = out_path.relative_to(Paths.BASE_DIR).as_posix()
    except ValueError:
        rel = str(out_path)
    return ArtifactTestGenResult(
        generated=True,
        rel_path=rel,
        message=f"Wrote artifact tests: {rel}",
        skipped_reason=None,
    )
