"""
End-to-end vertical slice: materialize vision/requirements/architecture/milestones,
then run preview → save reviewed plan → apply → gates.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from forge.design_manager import DesignManager, MilestoneService
from forge.executor import Executor
from forge.task_service import ensure_tasks_for_milestone, get_next_task
from forge.llm import LLMClient
from forge.llm_resolve import resolve_llm_client_from_policy
from forge.paths import Paths
from forge.planner_resolver import resolve_planner
from forge.policy_config import (
    PlannerPolicy,
    ReviewedApplyPolicy,
    load_planner_policy,
    load_reviewed_apply_policy,
    load_task_execution_policy,
    merge_reviewed_apply_policy,
)
from forge.planner import Planner
from forge.run_events import (
    ARTIFACT_WRITTEN,
    PHASE_COMPLETED,
    PHASE_STARTED,
    RUN_COMPLETED,
    RUN_FAILED,
    RUN_STARTED,
    as_emitter,
)
from forge.vision import VisionManager

# Shown in errors (stable path under Forge project layout).
MILESTONES_DOC_PATH = "docs/milestones.md"

_PLACEHOLDER_OBJECTIVE = (
    "_(placeholder — describe the measurable outcome of this milestone.)_"
)
_PLACEHOLDER_SCOPE = "_(placeholder — what is in vs out of scope.)_"
_PLACEHOLDER_VALIDATION = (
    "_(placeholder — observable checks proving this milestone is done.)_"
)

_MILESTONE_HEADER_RE = re.compile(r"^##\s+Milestone\s+(\d+)\s*:\s*.+$")


@dataclass(frozen=True)
class VerticalSliceBundle:
    vision: str
    requirements_md: str
    architecture_md: str
    milestones_md: str


TODO_CLI_DEMO = """#!/usr/bin/env python3
\"\"\"Minimal CLI todo demo generated by Forge vertical slice.\"\"\"
import argparse


def main() -> None:
    parser = argparse.ArgumentParser(description="Tiny todo CLI")
    parser.add_argument("--add", type=str, help="Add a todo item")
    args = parser.parse_args()
    if args.add:
        print(f"Added todo: {args.add}")
    else:
        print("Todo list empty. Use --add TEXT to add items.")


if __name__ == "__main__":
    main()
"""


def _escape_write_body(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "")


def demo_bundle() -> VerticalSliceBundle:
    write_action = f"write_file examples/todo_cli.py | {_escape_write_body(TODO_CLI_DEMO)}"
    milestones = f"""# Milestones

## Milestone 1: Ship minimal runnable todo CLI

- **Objective**: Add a runnable Python CLI under `examples/` that accepts `--add`.
- **Scope**: Single-file implementation; stdlib only.
- **Validation**: File exists, contains an entrypoint, and runs with exit code 0.

- **Forge Actions**:
  - {write_action}
  - append_section requirements Overview | **Vertical slice**: demo todo CLI (`examples/todo_cli.py`).
  - mark_milestone_completed
- **Forge Validation**:
  - path_file_contains examples/todo_cli.py def main
  - file_contains requirements Vertical slice
"""
    return VerticalSliceBundle(
        vision=(
            "Vertical slice demo: a tiny command-line todo utility under examples/ "
            "that prints helpful output and supports --add."
        ),
        requirements_md=(
            "# Requirements\n\n"
            "## Overview\n"
            "This demo project exists to prove Forge can generate and apply real code.\n\n"
            "## Functional\n"
            "- Provide `examples/todo_cli.py` runnable with `python examples/todo_cli.py`.\n"
            "- Support optional `--add <text>` to record a todo message.\n"
        ),
        architecture_md=(
            "# Architecture\n\n"
            "## Overview\n"
            "Single Python module under `examples/` using argparse. No external packages.\n"
        ),
        milestones_md=milestones,
    )


def _artifact_rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(Paths.BASE_DIR.resolve()).as_posix()
    except ValueError:
        return str(path)


def materialize_bundle(
    bundle: VerticalSliceBundle, *, event_bus: object | None = None
) -> None:
    bus = as_emitter(event_bus)
    Paths.ensure_project_structure()
    VisionManager.save_vision(bundle.vision)
    bus.emit(ARTIFACT_WRITTEN, path=_artifact_rel(Paths.VISION_FILE), kind="vision")
    DesignManager.save_document(Paths.REQUIREMENTS_FILE, bundle.requirements_md)
    bus.emit(
        ARTIFACT_WRITTEN, path=_artifact_rel(Paths.REQUIREMENTS_FILE), kind="requirements"
    )
    DesignManager.save_document(Paths.ARCHITECTURE_FILE, bundle.architecture_md)
    bus.emit(
        ARTIFACT_WRITTEN,
        path=_artifact_rel(Paths.ARCHITECTURE_FILE),
        kind="architecture",
    )
    DesignManager.save_document(Paths.MILESTONES_FILE, bundle.milestones_md)
    bus.emit(
        ARTIFACT_WRITTEN, path=_artifact_rel(Paths.MILESTONES_FILE), kind="milestones"
    )
    # Ensure milestones parse before planning
    MilestoneService.list_milestones()


def _last_nonempty_osv_line(rest: list[str], prefix: str) -> str:
    """Last non-empty value for a field, matching MilestoneService last-wins overwrite behavior."""
    last_nonempty = ""
    for line in rest:
        st = line.strip()
        if st.startswith(prefix):
            tail = line.split(":", 1)[1].strip() if ":" in line else ""
            if tail:
                last_nonempty = tail
    return last_nonempty


def _strip_osv_lines_from_rest(rest: list[str]) -> list[str]:
    out: list[str] = []
    for line in rest:
        st = line.strip()
        if st.startswith(
            (
                "- **Objective**:",
                "- **Scope**:",
                "- **Validation**:",
            )
        ):
            continue
        out.append(line)
    return out


def _repair_single_milestone_section(
    section: list[str], milestone_id: str
) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    depends: list[str] = []
    i = 0
    while i < len(section) and section[i].strip().startswith("- **Depends On**:"):
        depends.append(section[i])
        i += 1
    rest = section[i:]
    obj = _last_nonempty_osv_line(rest, "- **Objective**:")
    scope = _last_nonempty_osv_line(rest, "- **Scope**:")
    val = _last_nonempty_osv_line(rest, "- **Validation**:")
    other = _strip_osv_lines_from_rest(rest)
    body: list[str] = []
    body.extend(depends)
    if not obj.strip():
        obj = _PLACEHOLDER_OBJECTIVE
        warnings.append(
            f"Milestone {milestone_id}: inserted placeholder Objective (missing or empty)."
        )
    if not scope.strip():
        scope = _PLACEHOLDER_SCOPE
        warnings.append(
            f"Milestone {milestone_id}: inserted placeholder Scope (missing or empty)."
        )
    if not val.strip():
        val = _PLACEHOLDER_VALIDATION
        warnings.append(
            f"Milestone {milestone_id}: inserted placeholder Validation (missing or empty)."
        )
    body.append(f"- **Objective**: {obj}")
    body.append(f"- **Scope**: {scope}")
    body.append(f"- **Validation**: {val}")
    body.extend(other)
    return body, warnings


def repair_llm_milestones_md(md: str) -> tuple[str, list[str]]:
    """
    Ensure each ``## Milestone N:`` section has non-empty Objective, Scope, and Validation.
    Inserts minimal placeholder text when the LLM omitted or emptied a field.
    Returns ``(repaired_markdown, warning_messages)``.
    """
    if not (md or "").strip():
        return md, []
    lines = md.splitlines()
    out: list[str] = []
    warnings: list[str] = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        st = line.strip()
        if st.startswith("## Milestone") and _MILESTONE_HEADER_RE.match(st):
            m = _MILESTONE_HEADER_RE.match(st)
            assert m is not None
            mid = m.group(1)
            out.append(line)
            i += 1
            start = i
            while i < n:
                t = lines[i].strip()
                if t.startswith("## Milestone") and _MILESTONE_HEADER_RE.match(t):
                    break
                i += 1
            section = lines[start:i]
            fixed, w = _repair_single_milestone_section(section, mid)
            warnings.extend(w)
            out.extend(fixed)
        else:
            out.append(line)
            i += 1
    repaired = "\n".join(out)
    if md.endswith("\n"):
        repaired += "\n"
    return repaired, warnings


def finalize_llm_milestones_md(raw_md: str) -> tuple[str, list[str]]:
    """
    Repair common LLM omissions, parse, and raise a clear error if still invalid.
    Returns ``(milestones_md_to_persist, repair_warnings)``.
    """
    repaired, repair_warnings = repair_llm_milestones_md(raw_md)
    try:
        MilestoneService.parse_milestones(repaired)
    except ValueError as exc:
        raise ValueError(
            f"{exc} See {MILESTONES_DOC_PATH} for the expected milestone shape; fix the "
            "markdown or re-run `forge vertical-slice` with a clearer idea/vision."
        ) from exc
    return repaired, repair_warnings


def _milestones_strict_example_block() -> str:
    return (
        "STRICT STRUCTURE (non-negotiable):\n"
        "- EVERY milestone MUST include these three bullets, in this order, IMMEDIATELY after "
        "any '- **Depends On**:' lines and BEFORE '- **Forge Actions**:'.\n"
        "- Use EXACTLY these labels (bold markers as shown). NEVER omit, rename, or leave empty.\n"
        "- **Objective**: one or more sentences: what this milestone delivers.\n"
        "- **Scope**: boundaries, tech constraints, files/areas touched.\n"
        "- **Validation**: how you will verify the milestone is complete (observable checks).\n\n"
        "STRICT EXAMPLE (mirror this structure for Milestone 1 and any further milestones):\n"
        "# Milestones\n\n"
        "## Milestone 1: Example title\n"
        "- **Objective**: Ship a minimal runnable example under examples/.\n"
        "- **Scope**: Single module; stdlib only; no new dependencies.\n"
        "- **Validation**: Example file exists, runs with exit code 0, and contains the entrypoint.\n"
        "- **Forge Actions**:\n"
        "  - write_file examples/example_app.py | def main():\\n    print('ok')\\n\n"
        "  - mark_milestone_completed\n"
        "- **Forge Validation**:\n"
        "  - path_file_contains examples/example_app.py def main\n\n"
    )


def _milestones_rules_block() -> str:
    return (
        _milestones_strict_example_block()
        + "Additional rules for milestones_md:\n"
        "- Start with '# Milestones' then '## Milestone 1: <title>'.\n"
        "- Include '- **Forge Actions**:' with one or more actions using ONLY:\n"
        "  append_section, replace_section, write_file, insert_after_in_file, insert_before_in_file,\n"
        "  replace_text_in_file, replace_block_in_file, replace_lines_in_file, add_decision, mark_milestone_completed\n"
        "- write_file format: write_file <rel_path> | <body with literal backslash-n for newlines>\n"
        "- Bounded edits: use @@FORGE@@ separators; optional trailing | occurrence=N must_be_unique=false line_match=true\n"
        "- Paths MUST start with examples/, src/, scripts/, or tests/.\n"
        "- Include '- **Forge Validation**:' with file_contains / section_contains / "
        "path_file_contains rules.\n"
        "- path_file_contains format: path_file_contains <rel_path> <substring>\n"
        "- End actions with mark_milestone_completed when appropriate.\n\n"
    )


def _build_idea_prompt(idea: str) -> str:
    return (
        "You are Forge. Produce a small vertical slice for the user's idea.\n"
        "Return ONLY JSON (no markdown fences) with this shape:\n"
        '{"vision": "<short string>", "requirements_md": "<markdown>", '
        '"architecture_md": "<markdown>", "milestones_md": "<markdown>"}\n\n'
        + _milestones_rules_block()
        + f"User idea:\n{idea.strip()}\n"
    )


def _build_fixed_vision_prompt(vision: str) -> str:
    return (
        "You are Forge. The following text is the AUTHORITATIVE project vision.\n"
        "Do not rewrite, summarize, or replace it in your output; you will not return a vision field.\n"
        "Generate requirements, architecture, and milestones that implement this vision.\n"
        "Return ONLY JSON (no markdown fences) with this shape:\n"
        '{"requirements_md": "<markdown>", "architecture_md": "<markdown>", '
        '"milestones_md": "<markdown>"}\n\n'
        + _milestones_rules_block()
        + "Authoritative vision:\n\n"
        f"{vision.strip()}\n"
    )


def read_vision_file_text(path: Path) -> str:
    """
    Load vision text from a file. Raises FileNotFoundError or ValueError with
    a message suitable for CLI display.
    """
    if not path.exists():
        raise FileNotFoundError(f"Vision file does not exist: {path}")
    if not path.is_file():
        raise ValueError(f"Vision path is not a file: {path}")
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise OSError(f"Could not read vision file {path}: {exc}") from exc
    text = raw.strip()
    if not text:
        raise ValueError(f"Vision file is empty (no non-whitespace content): {path}")
    return text


def resolve_vision_file_path(path_str: str, *, base_dir: Path) -> Path:
    """Resolve CLI --vision-file to an absolute path (absolute paths unchanged)."""
    p = Path(path_str)
    return p if p.is_absolute() else (base_dir / p).resolve()


def _review_enforcement_status(
    planner: Planner, policy: PlannerPolicy, *, save_plan: bool
) -> dict:
    enabled = bool(getattr(policy, "require_review_for_nondeterministic", False))
    required = bool(planner.metadata().get("is_nondeterministic"))
    compliant = (not enabled) or (not required) or bool(save_plan)
    return {
        "enabled": enabled,
        "required_for_plan": required and enabled,
        "compliant": compliant,
        "requires_save_plan": bool(enabled and required),
    }


def _parse_vertical_slice_json(
    raw: str, *, required_keys: tuple[str, ...]
) -> dict[str, object]:
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"LLM returned invalid JSON for vertical slice: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("LLM vertical slice JSON must be an object.")
    missing = [k for k in required_keys if k not in data]
    if missing:
        raise ValueError(f"LLM JSON missing keys: {missing}")
    return data


def generate_bundle_from_llm(idea: str, client: LLMClient) -> VerticalSliceBundle:
    raw = client.generate(_build_idea_prompt(idea))
    data = _parse_vertical_slice_json(
        raw, required_keys=("vision", "requirements_md", "architecture_md", "milestones_md")
    )
    milestones_md, _mw = finalize_llm_milestones_md(str(data["milestones_md"]))
    bundle = VerticalSliceBundle(
        vision=str(data["vision"]),
        requirements_md=str(data["requirements_md"]),
        architecture_md=str(data["architecture_md"]),
        milestones_md=milestones_md,
    )
    return bundle


def generate_bundle_from_llm_fixed_vision(vision_text: str, client: LLMClient) -> VerticalSliceBundle:
    """
    LLM generates requirements, architecture, and milestones only; ``vision_text`` is
    the source of truth and is not regenerated by the model.
    """
    raw = client.generate(_build_fixed_vision_prompt(vision_text))
    data = _parse_vertical_slice_json(
        raw, required_keys=("requirements_md", "architecture_md", "milestones_md")
    )
    milestones_md, _mw = finalize_llm_milestones_md(str(data["milestones_md"]))
    bundle = VerticalSliceBundle(
        vision=vision_text.strip(),
        requirements_md=str(data["requirements_md"]),
        architecture_md=str(data["architecture_md"]),
        milestones_md=milestones_md,
    )
    return bundle


def resolve_docs_llm_client() -> tuple[LLMClient | None, str | None]:
    policy, err = load_planner_policy()
    if err:
        return None, err
    if not policy.llm_client:
        return None, (
            "Vertical slice LLM docs (--idea, --vision-file, --from-vision) require "
            "planner.llm_client in forge-policy.json "
            "(e.g. 'openai' with API key, or 'stub' for offline testing)."
        )
    return resolve_llm_client_from_policy(policy)


def _failure_reason_from_apply(apply_res: dict) -> str:
    msg = apply_res.get("message")
    if msg:
        return str(msg)
    if not apply_res.get("apply_ok", True):
        errs = apply_res.get("errors") or []
        return "; ".join(str(e) for e in errs) or "apply failed"
    return str(apply_res.get("gate_summary") or "validation failed")


def run_vertical_slice(
    *,
    demo: bool,
    idea: str | None,
    fixed_vision: str | None = None,
    milestone_id: int,
    planner_mode: str | None,
    gate_validate: bool | None,
    gate_test_cmd: str | None,
    disable_gate_test_cmd: bool,
    gate_test_timeout_seconds: int | None,
    gate_test_output_max_chars: int | None,
    event_bus: object | None = None,
) -> dict:
    """
    Run materialize → save reviewed plan → apply with gates.
    Returns a dict with ok, stages (list), plan_id, etc.

    When ``demo`` is False, provide exactly one of ``idea`` (CLI ``--idea``) or
    ``fixed_vision`` (file-driven vision; vision text is not LLM-regenerated).
    """
    bus = as_emitter(event_bus)
    stages: list[dict] = []

    if demo:
        input_mode = "demo"
    elif fixed_vision is not None:
        input_mode = "vision_file"
    else:
        input_mode = "idea"

    bus.emit(
        RUN_STARTED,
        command="vertical-slice",
        demo=demo,
        has_idea=idea is not None,
        fixed_vision=bool(fixed_vision),
        input_mode=input_mode,
        milestone_id=milestone_id,
    )

    try:
        if demo:
            bus.emit(
                PHASE_STARTED,
                phase="materialize_docs",
                label="write vision, requirements, architecture, milestones (demo)",
            )
            bundle = demo_bundle()
            materialize_bundle(bundle, event_bus=bus)
            stages.append(
                {
                    "stage": "materialize_docs",
                    "ok": True,
                    "mode": "demo",
                    "message": "Wrote vision, requirements, architecture, milestones (demo bundle).",
                }
            )
            bus.emit(PHASE_COMPLETED, phase="materialize_docs", ok=True)
        else:
            if idea is not None and fixed_vision is not None:
                raise AssertionError(
                    "run_vertical_slice: idea and fixed_vision are mutually exclusive"
                )
            if idea is None and fixed_vision is None:
                raise AssertionError(
                    "run_vertical_slice: need idea or fixed_vision when demo is False"
                )
            doc_mode = "vision_file" if fixed_vision is not None else "idea"
            client, err = resolve_docs_llm_client()
            if err or client is None:
                msg = err or "No LLM client available."
                stages.append(
                    {
                        "stage": "materialize_docs",
                        "ok": False,
                        "mode": doc_mode,
                        "message": msg,
                    }
                )
                bus.emit(RUN_FAILED, reason=msg, phase="materialize_docs")
                bus.emit(RUN_COMPLETED, ok=False)
                return _finalize(stages, ok=False)
            gen_label = (
                "generate requirements, architecture, milestones from vision file"
                if fixed_vision is not None
                else "generate specs and milestones from idea"
            )
            bus.emit(
                PHASE_STARTED,
                phase="llm_generation",
                label=gen_label,
            )
            try:
                if fixed_vision is not None:
                    bundle = generate_bundle_from_llm_fixed_vision(fixed_vision, client)
                else:
                    bundle = generate_bundle_from_llm(idea, client)
            except ValueError as exc:
                stages.append(
                    {
                        "stage": "materialize_docs",
                        "ok": False,
                        "mode": doc_mode,
                        "message": str(exc),
                    }
                )
                bus.emit(PHASE_COMPLETED, phase="llm_generation", ok=False, message=str(exc))
                bus.emit(RUN_FAILED, reason=str(exc), phase="llm_generation")
                bus.emit(RUN_COMPLETED, ok=False)
                return _finalize(stages, ok=False)
            bus.emit(PHASE_COMPLETED, phase="llm_generation", ok=True)
            bus.emit(
                PHASE_STARTED,
                phase="materialize_docs",
                label="write vision, requirements, architecture, milestones",
            )
            try:
                materialize_bundle(bundle, event_bus=bus)
            except OSError as exc:
                msg = f"Failed to write docs: {exc}"
                stages.append(
                    {
                        "stage": "materialize_docs",
                        "ok": False,
                        "mode": doc_mode,
                        "message": msg,
                    }
                )
                bus.emit(PHASE_COMPLETED, phase="materialize_docs", ok=False, message=msg)
                bus.emit(RUN_FAILED, reason=msg, phase="materialize_docs")
                bus.emit(RUN_COMPLETED, ok=False)
                return _finalize(stages, ok=False)
            wrote_msg = (
                "Wrote vision (from file), requirements, architecture, milestones (LLM)."
                if doc_mode == "vision_file"
                else "Wrote vision, requirements, architecture, milestones (LLM)."
            )
            stages.append(
                {
                    "stage": "materialize_docs",
                    "ok": True,
                    "mode": doc_mode,
                    "message": wrote_msg,
                }
            )
            bus.emit(PHASE_COMPLETED, phase="materialize_docs", ok=True)
    except Exception as exc:  # noqa: BLE001
        stages.append(
            {
                "stage": "materialize_docs",
                "ok": False,
                "message": str(exc),
            }
        )
        bus.emit(RUN_FAILED, reason=str(exc), phase="materialize_docs")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    planner, eff_planner_policy, planner_err = resolve_planner(mode_override=planner_mode)
    if planner_err or planner is None or eff_planner_policy is None:
        msg = planner_err or "Planner unavailable."
        stages.append(
            {
                "stage": "preview_save_plan",
                "ok": False,
                "message": msg,
            }
        )
        bus.emit(RUN_FAILED, reason=msg, phase="plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    enforcement = _review_enforcement_status(
        planner, eff_planner_policy, save_plan=True
    )
    bus.emit(
        PHASE_STARTED,
        phase="plan",
        label="ensure tasks, preview next task, save reviewed plan",
    )
    expand = ensure_tasks_for_milestone(milestone_id)
    if not expand.get("ok"):
        stages.append({"stage": "task_expand", **expand})
        bus.emit(RUN_FAILED, reason=expand.get("message", "task expand failed"), phase="plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)
    nt = get_next_task(milestone_id)
    if nt is None:
        msg = f"No pending tasks for milestone {milestone_id}."
        stages.append({"stage": "preview_save_plan", "ok": False, "message": msg})
        bus.emit(RUN_FAILED, reason=msg, phase="plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)
    preview = Executor.save_reviewed_plan_for_task(
        milestone_id,
        nt.id,
        planner=planner,
        review_enforcement=enforcement,
        event_bus=bus,
    )
    stages.append({"stage": "preview_save_plan", **preview})
    bus.emit(
        PHASE_COMPLETED,
        phase="plan",
        ok=bool(preview.get("ok")),
        message=preview.get("message"),
    )
    if not preview.get("ok"):
        reason = str(preview.get("message") or "plan preview or save failed")
        bus.emit(RUN_FAILED, reason=reason, phase="plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    plan_id = preview.get("plan_id")
    if not plan_id:
        msg = "No plan_id from preview/save step."
        stages.append({"stage": "apply_plan", "ok": False, "message": msg})
        bus.emit(RUN_FAILED, reason=msg, phase="plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    base_policy, policy_err = load_reviewed_apply_policy()
    if policy_err:
        stages.append({"stage": "apply_plan", "ok": False, "message": policy_err})
        bus.emit(RUN_FAILED, reason=policy_err, phase="apply_plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    gv = gate_validate if gate_validate is not None else True
    cmd_override = gate_test_cmd
    if not disable_gate_test_cmd and cmd_override is None and demo:
        cmd_override = "python examples/todo_cli.py"

    resolved: ReviewedApplyPolicy = merge_reviewed_apply_policy(
        base_policy,
        gate_validate=gv,
        test_command=cmd_override,
        disable_test_command=disable_gate_test_cmd,
        test_timeout_seconds=gate_test_timeout_seconds,
        test_output_max_chars=gate_test_output_max_chars,
    )
    if resolved.test_timeout_seconds <= 0 or resolved.test_output_max_chars <= 0:
        msg = "Invalid gate timeout or output max chars."
        stages.append({"stage": "apply_plan", "ok": False, "message": msg})
        bus.emit(RUN_FAILED, reason=msg, phase="apply_plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    task_exec_policy, task_exec_err = load_task_execution_policy()
    if task_exec_err:
        stages.append({"stage": "apply_plan", "ok": False, "message": task_exec_err})
        bus.emit(RUN_FAILED, reason=task_exec_err, phase="apply_plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    scope = Executor.task_ids_for_reviewed_plan(plan_id)
    if scope is None:
        msg = f"Reviewed plan '{plan_id}' not found."
        stages.append({"stage": "apply_plan", "ok": False, "message": msg})
        bus.emit(RUN_FAILED, reason=msg, phase="apply_plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)
    vm_id, vt_id = scope
    try:
        vm_milestone = MilestoneService.get_milestone(vm_id)
    except ValueError as exc:
        stages.append({"stage": "apply_plan", "ok": False, "message": str(exc)})
        bus.emit(RUN_FAILED, reason=str(exc), phase="apply_plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)
    if not vm_milestone:
        msg = "Milestone for reviewed plan no longer exists."
        stages.append({"stage": "apply_plan", "ok": False, "message": msg})
        bus.emit(RUN_FAILED, reason=msg, phase="apply_plan")
        bus.emit(RUN_COMPLETED, ok=False)
        return _finalize(stages, ok=False)

    bus.emit(PHASE_STARTED, phase="apply", label="apply reviewed plan (repair loop)")
    apply_res = Executor.run_task_apply_with_repair_loop(
        vm_id,
        vt_id,
        vm_milestone,
        planner=planner,
        apply_policy=resolved,
        task_exec_policy=task_exec_policy,
        run_milestone_validation=resolved.run_validation_gate,
        initial_plan_id=plan_id,
        review_enforcement=enforcement,
        event_bus=bus,
        finalize_milestone_state_on_failure=False,
        milestone_state=None,
        state=None,
        state_file=None,
    )
    bus.emit(
        PHASE_COMPLETED,
        phase="apply",
        ok=bool(apply_res.get("ok")),
        message=apply_res.get("message"),
    )
    stages.append({"stage": "apply_plan", **apply_res})
    ok = bool(apply_res.get("ok"))
    if not ok:
        bus.emit(
            RUN_FAILED,
            reason=_failure_reason_from_apply(apply_res),
            phase="apply_or_validation",
        )
    bus.emit(RUN_COMPLETED, ok=ok)
    return _finalize(stages, ok=ok, plan_id=plan_id)


def _finalize(
    stages: list[dict], *, ok: bool, plan_id: str | None = None
) -> dict:
    return {
        "command": "vertical-slice",
        "ok": ok,
        "plan_id": plan_id or next(
            (s.get("plan_id") for s in stages if s.get("plan_id")), None
        ),
        "stages": stages,
    }
