"""
End-to-end vertical slice: materialize vision/requirements/architecture/milestones,
then run preview → save reviewed plan → apply → gates.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from forge.design_manager import DesignManager, MilestoneService
from forge.executor import Executor
from forge.llm import LLMClient
from forge.llm_resolve import resolve_llm_client_from_policy
from forge.paths import Paths
from forge.planner_resolver import resolve_planner
from forge.policy_config import (
    PlannerPolicy,
    ReviewedApplyPolicy,
    load_planner_policy,
    load_reviewed_apply_policy,
    merge_reviewed_apply_policy,
)
from forge.planner import Planner
from forge.vision import VisionManager


@dataclass(frozen=True)
class VerticalSliceBundle:
    vision: str
    requirements_md: str
    architecture_md: str
    milestones_md: str


TODO_CLI_DEMO = """#!/usr/bin/env python3
\"\"\"Minimal CLI todo demo generated by Forge vertical slice.\"\"\"
import argparse


def main() -> None:
    parser = argparse.ArgumentParser(description="Tiny todo CLI")
    parser.add_argument("--add", type=str, help="Add a todo item")
    args = parser.parse_args()
    if args.add:
        print(f"Added todo: {args.add}")
    else:
        print("Todo list empty. Use --add TEXT to add items.")


if __name__ == "__main__":
    main()
"""


def _escape_write_body(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "")


def demo_bundle() -> VerticalSliceBundle:
    write_action = f"write_file examples/todo_cli.py | {_escape_write_body(TODO_CLI_DEMO)}"
    milestones = f"""# Milestones

## Milestone 1: Ship minimal runnable todo CLI

- **Objective**: Add a runnable Python CLI under `examples/` that accepts `--add`.
- **Scope**: Single-file implementation; stdlib only.
- **Validation**: File exists, contains an entrypoint, and runs with exit code 0.

- **Forge Actions**:
  - {write_action}
  - append_section requirements Overview | **Vertical slice**: demo todo CLI (`examples/todo_cli.py`).
  - mark_milestone_completed
- **Forge Validation**:
  - path_file_contains examples/todo_cli.py def main
  - file_contains requirements Vertical slice
"""
    return VerticalSliceBundle(
        vision=(
            "Vertical slice demo: a tiny command-line todo utility under examples/ "
            "that prints helpful output and supports --add."
        ),
        requirements_md=(
            "# Requirements\n\n"
            "## Overview\n"
            "This demo project exists to prove Forge can generate and apply real code.\n\n"
            "## Functional\n"
            "- Provide `examples/todo_cli.py` runnable with `python examples/todo_cli.py`.\n"
            "- Support optional `--add <text>` to record a todo message.\n"
        ),
        architecture_md=(
            "# Architecture\n\n"
            "## Overview\n"
            "Single Python module under `examples/` using argparse. No external packages.\n"
        ),
        milestones_md=milestones,
    )


def materialize_bundle(bundle: VerticalSliceBundle) -> None:
    Paths.ensure_project_structure()
    VisionManager.save_vision(bundle.vision)
    DesignManager.save_document(Paths.REQUIREMENTS_FILE, bundle.requirements_md)
    DesignManager.save_document(Paths.ARCHITECTURE_FILE, bundle.architecture_md)
    DesignManager.save_document(Paths.MILESTONES_FILE, bundle.milestones_md)
    # Ensure milestones parse before planning
    MilestoneService.list_milestones()


def _build_idea_prompt(idea: str) -> str:
    return (
        "You are Forge. Produce a small vertical slice for the user's idea.\n"
        "Return ONLY JSON (no markdown fences) with this shape:\n"
        '{"vision": "<short string>", "requirements_md": "<markdown>", '
        '"architecture_md": "<markdown>", "milestones_md": "<markdown>"}\n\n'
        "Rules for milestones_md:\n"
        "- Start with '# Milestones' then '## Milestone 1: <title>'.\n"
        "- Include bullet fields: Objective, Scope, Validation.\n"
        "- Include '- **Forge Actions**:' with one or more actions using ONLY:\n"
        "  append_section, replace_section, write_file, add_decision, mark_milestone_completed\n"
        "- write_file format: write_file <rel_path> | <body with literal backslash-n for newlines>\n"
        "- Paths for write_file MUST start with examples/, src/, scripts/, or tests/.\n"
        "- Include '- **Forge Validation**:' with file_contains / section_contains / "
        "path_file_contains rules.\n"
        "- path_file_contains format: path_file_contains <rel_path> <substring>\n"
        "- End actions with mark_milestone_completed when appropriate.\n\n"
        f"User idea:\n{idea.strip()}\n"
    )


def _review_enforcement_status(
    planner: Planner, policy: PlannerPolicy, *, save_plan: bool
) -> dict:
    enabled = bool(getattr(policy, "require_review_for_nondeterministic", False))
    required = bool(planner.metadata().get("is_nondeterministic"))
    compliant = (not enabled) or (not required) or bool(save_plan)
    return {
        "enabled": enabled,
        "required_for_plan": required and enabled,
        "compliant": compliant,
        "requires_save_plan": bool(enabled and required),
    }


def generate_bundle_from_llm(idea: str, client: LLMClient) -> VerticalSliceBundle:
    raw = client.generate(_build_idea_prompt(idea))
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(f"LLM returned invalid JSON for vertical slice: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("LLM vertical slice JSON must be an object.")
    keys = ("vision", "requirements_md", "architecture_md", "milestones_md")
    missing = [k for k in keys if k not in data]
    if missing:
        raise ValueError(f"LLM JSON missing keys: {missing}")
    bundle = VerticalSliceBundle(
        vision=str(data["vision"]),
        requirements_md=str(data["requirements_md"]),
        architecture_md=str(data["architecture_md"]),
        milestones_md=str(data["milestones_md"]),
    )
    MilestoneService.parse_milestones(bundle.milestones_md)
    return bundle


def resolve_docs_llm_client() -> tuple[LLMClient | None, str | None]:
    policy, err = load_planner_policy()
    if err:
        return None, err
    if not policy.llm_client:
        return None, (
            "Vertical slice --idea requires planner.llm_client in forge-policy.json "
            "(e.g. 'openai' with API key, or 'stub' for offline testing)."
        )
    return resolve_llm_client_from_policy(policy)


def run_vertical_slice(
    *,
    demo: bool,
    idea: str | None,
    milestone_id: int,
    planner_mode: str | None,
    gate_validate: bool | None,
    gate_test_cmd: str | None,
    disable_gate_test_cmd: bool,
    gate_test_timeout_seconds: int | None,
    gate_test_output_max_chars: int | None,
) -> dict:
    """
    Run materialize → save reviewed plan → apply with gates.
    Returns a dict with ok, stages (list), plan_id, etc.
    """
    stages: list[dict] = []

    try:
        if demo:
            bundle = demo_bundle()
            materialize_bundle(bundle)
            stages.append(
                {
                    "stage": "materialize_docs",
                    "ok": True,
                    "mode": "demo",
                    "message": "Wrote vision, requirements, architecture, milestones (demo bundle).",
                }
            )
        else:
            assert idea is not None
            client, err = resolve_docs_llm_client()
            if err or client is None:
                stages.append(
                    {
                        "stage": "materialize_docs",
                        "ok": False,
                        "mode": "idea",
                        "message": err or "No LLM client available.",
                    }
                )
                return _finalize(stages, ok=False)
            try:
                bundle = generate_bundle_from_llm(idea, client)
            except ValueError as exc:
                stages.append(
                    {
                        "stage": "materialize_docs",
                        "ok": False,
                        "mode": "idea",
                        "message": str(exc),
                    }
                )
                return _finalize(stages, ok=False)
            try:
                materialize_bundle(bundle)
            except OSError as exc:
                stages.append(
                    {
                        "stage": "materialize_docs",
                        "ok": False,
                        "mode": "idea",
                        "message": f"Failed to write docs: {exc}",
                    }
                )
                return _finalize(stages, ok=False)
            stages.append(
                {
                    "stage": "materialize_docs",
                    "ok": True,
                    "mode": "idea",
                    "message": "Wrote vision, requirements, architecture, milestones (LLM).",
                }
            )
    except Exception as exc:  # noqa: BLE001
        stages.append(
            {
                "stage": "materialize_docs",
                "ok": False,
                "message": str(exc),
            }
        )
        return _finalize(stages, ok=False)

    planner, eff_planner_policy, planner_err = resolve_planner(mode_override=planner_mode)
    if planner_err or planner is None or eff_planner_policy is None:
        stages.append(
            {
                "stage": "preview_save_plan",
                "ok": False,
                "message": planner_err or "Planner unavailable.",
            }
        )
        return _finalize(stages, ok=False)

    enforcement = _review_enforcement_status(
        planner, eff_planner_policy, save_plan=True
    )
    preview = Executor.save_reviewed_plan_for_milestone(
        milestone_id, planner=planner, review_enforcement=enforcement
    )
    stages.append({"stage": "preview_save_plan", **preview})
    if not preview.get("ok"):
        return _finalize(stages, ok=False)

    plan_id = preview.get("plan_id")
    if not plan_id:
        stages.append(
            {
                "stage": "apply_plan",
                "ok": False,
                "message": "No plan_id from preview/save step.",
            }
        )
        return _finalize(stages, ok=False)

    base_policy, policy_err = load_reviewed_apply_policy()
    if policy_err:
        stages.append({"stage": "apply_plan", "ok": False, "message": policy_err})
        return _finalize(stages, ok=False)

    gv = gate_validate if gate_validate is not None else True
    cmd_override = gate_test_cmd
    if not disable_gate_test_cmd and cmd_override is None and demo:
        cmd_override = "python examples/todo_cli.py"

    resolved: ReviewedApplyPolicy = merge_reviewed_apply_policy(
        base_policy,
        gate_validate=gv,
        test_command=cmd_override,
        disable_test_command=disable_gate_test_cmd,
        test_timeout_seconds=gate_test_timeout_seconds,
        test_output_max_chars=gate_test_output_max_chars,
    )
    if resolved.test_timeout_seconds <= 0 or resolved.test_output_max_chars <= 0:
        stages.append(
            {
                "stage": "apply_plan",
                "ok": False,
                "message": "Invalid gate timeout or output max chars.",
            }
        )
        return _finalize(stages, ok=False)

    apply_res = Executor.apply_reviewed_plan_with_gates(
        plan_id,
        run_validation_gate=resolved.run_validation_gate,
        test_command=resolved.test_command,
        test_timeout_seconds=resolved.test_timeout_seconds,
        test_output_max_chars=resolved.test_output_max_chars,
    )
    stages.append({"stage": "apply_plan", **apply_res})
    ok = bool(apply_res.get("ok"))
    return _finalize(stages, ok=ok, plan_id=plan_id)


def _finalize(
    stages: list[dict], *, ok: bool, plan_id: str | None = None
) -> dict:
    return {
        "command": "vertical-slice",
        "ok": ok,
        "plan_id": plan_id or next(
            (s.get("plan_id") for s in stages if s.get("plan_id")), None
        ),
        "stages": stages,
    }
